name: khqrcode
description: Cambodia KHQR (QR Code Payment) library for Dart/Flutter. Generate and decode KHQR codes for Bakong payment system.
version: 1.0.0
homepage: https://github.com/yourusername/khqrcode
repository: https://github.com/yourusername/khqrcode

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
